# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  frontend:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./forgettable-frontend/ # Set directory of workflow commands

    env:
      CI: "false"
      node-version: 16

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
    
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - run: npm ci 
    - run: npx eslint --ext .js,.jsx,.ts,.tsx .
    - run: npm run test
    - run: npm run build --if-present

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend/ # Set directory of workflow commands

    
    env:
      CI: "false"
      node-version: 16

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - name: "Create .env file from secrets"
      run: |
        cd ./backend
        touch .env
        echo "FIREBASE_TEST_AUTH_EMAIL=${{ secrets.FIREBASE_TEST_AUTH_EMAIL }}" >> .env
        echo "FIREBASE_TEST_AUTH_KEY=${{ secrets.FIREBASE_TEST_AUTH_KEY }}" >> .env
        echo "FIREBASE_TEST_AUTH_PASS=${{ secrets.FIREBASE_TEST_AUTH_PASS }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
      
    - run: npm ci
    - run: npm run lint
    - run: npm run test
