# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend_ci

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  frontend:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./forgettable-frontend/ # Set directory of workflow commands

    env:
      node-version: 16

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
    
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - run: npm ci 
    - run: npx eslint --ext .js,.jsx,.ts,.tsx .
    - run: |
        cd /src
        touch firebase-config.js
        cd ..
        npm run test
    - run: npm run build --if-present
